### ISSUE TITLE
KeyError: 'salary'

### ISSUE THREAD

**Issue by timurka** [capitanov/hh_research#7]
Добрый вечер!
Спасибо большое за скрипт. Он работает, но иногда (и вот сейчас постоянно) выдает ошибку в консоли:

```
[root]# python3.6 researcher.py --text "Data scientists" --refresh --save_result
[INFO]: Get exchange rates: {'USD': 0.012641, 'EUR': 0.010831, 'UAH': 0.35902, 'RUR': 1}
[INFO]: Collect data from JSON. Create list of vacancies...
Get data via HH API:   0%|                                                  | 0/237 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "researcher.py", line 97, in <module>
    hh_analyzer()
  File "researcher.py", line 82, in __call__
    query=self.settings.options, refresh=self.settings.refresh, max_workers=self.settings.max_workers
  File "/hh/src/data_collector.py", line 178, in collect_vacancies
    executor.map(self.get_vacancy, ids), desc="Get data via HH API", ncols=100, total=len(ids),
  File "/usr/local/lib/python3.6/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/hh/src/data_collector.p", line 104, in get_vacancy
    salary = vacancy["salary"]
KeyError: 'salary'
```

В чём может быть причина?

**Comment by hukenovs** [comment]
Приветствую! 

Скорее всего при парсинге вакансии через API отсутствует поле salary.
Я поправил это и сделал так: `vacancy.get('salary')`. Но у себя воспроизвести это поведение не смог.
Попробуйте.
